{"uid":"bf47ba054fe53f69","name":"An uncaught error was detected outside of a test","fullName":"cypress/e2e/cartCheckoutPayment.cy.js#An uncaught error was detected outside of a test","historyId":"34c4a9f0448e3dc551cd278b5f1c698c:d41d8cd98f00b204e9800998ecf8427e","time":{"start":1735980002733,"stop":1735980003886,"duration":1153},"status":"broken","statusMessage":"The following error originated from your test code, not from Cypress.\n\n  > Cannot call `cy.then()` outside a running test.\n\nThis usually happens when you accidentally write commands outside an `it(...)` test.\n\nIf that is the case, just move these commands inside an `it(...)` test.\n\nCheck your test file for errors.\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.\n\nhttps://on.cypress.io/cannot-execute-commands-outside-test","statusTrace":"CypressError: The following error originated from your test code, not from Cypress.\n\n  > Cannot call `cy.then()` outside a running test.\n\nThis usually happens when you accidentally write commands outside an `it(...)` test.\n\nIf that is the case, just move these commands inside an `it(...)` test.\n\nCheck your test file for errors.\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.\n\nhttps://on.cypress.io/cannot-execute-commands-outside-test\n    at ensureRunnable (https://automationexercise.com/__cypress/runner/cypress_runner.js:137633:58)\n    at cy.<computed> [as then] (https://automationexercise.com/__cypress/runner/cypress_runner.js:138118:7)\n    at <unknown> (https://automationexercise.com/__cypress/runner/cypress_runner.js:111806:23)\n    at tryCatcher (https://automationexercise.com/__cypress/runner/cypress_runner.js:1830:23)\n    at Object.gotValue (https://automationexercise.com/__cypress/runner/cypress_runner.js:6499:18)\n    at Object.gotAccum (https://automationexercise.com/__cypress/runner/cypress_runner.js:6488:25)\n    at Object.tryCatcher (https://automationexercise.com/__cypress/runner/cypress_runner.js:1830:23)\n    at Promise._settlePromiseFromHandler (https://automationexercise.com/__cypress/runner/cypress_runner.js:1542:31)\n    at Promise._settlePromise (https://automationexercise.com/__cypress/runner/cypress_runner.js:1599:18)\n    at Promise._settlePromise0 (https://automationexercise.com/__cypress/runner/cypress_runner.js:1644:10)\n    at Promise._settlePromises (https://automationexercise.com/__cypress/runner/cypress_runner.js:1724:18)\n    at _drainQueueStep (https://automationexercise.com/__cypress/runner/cypress_runner.js:2430:12)\n    at _drainQueue (https://automationexercise.com/__cypress/runner/cypress_runner.js:2423:9)\n    at Async._drainQueues (https://automationexercise.com/__cypress/runner/cypress_runner.js:2439:5)\n    at Async.drainQueues (https://automationexercise.com/__cypress/runner/cypress_runner.js:2309:14)","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":1,"retriesStatusChange":false,"beforeStages":[{"name":"\"before each\" hook","time":{"start":1735980002748,"stop":1735980003696,"duration":948},"status":"passed","steps":[{"name":"visit /","time":{"start":1735980002854,"stop":1735980003630,"duration":776},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"Resolved Url","value":"https://automationexercise.com/"},{"name":"Redirects","value":"[]"},{"name":"Cookies Set","value":"[]"}],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":true},{"name":"url","time":{"start":1735980003631,"stop":1735980003634,"duration":3},"status":"passed","steps":[{"name":"assert expected https://automationexercise.com/ to equal https://automationexercise.com/","time":{"start":1735980003634,"stop":1735980003634,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"actual","value":"https://automationexercise.com/"},{"name":"expected","value":"https://automationexercise.com/"}],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":true}],"attachments":[],"parameters":[{"name":"Yielded","value":"https://automationexercise.com/"}],"shouldDisplayMessage":false,"stepsCount":1,"attachmentsCount":0,"hasContent":true},{"name":"get .fa-home","time":{"start":1735980003636,"stop":1735980003650,"duration":14},"status":"passed","steps":[{"name":"assert expected <i.fa.fa-home> to have CSS property color with the value rgb(255, 165, 0)","time":{"start":1735980003649,"stop":1735980003650,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"actual","value":"rgb(255, 165, 0)"},{"name":"expected","value":"rgb(255, 165, 0)"},{"name":"subject","value":"<i class=\"fa fa-home\"></i>"}],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":true}],"attachments":[],"parameters":[{"name":"Selector","value":".fa-home"},{"name":"Yielded","value":"<i class=\"fa fa-home\"></i>"},{"name":"Elements","value":"1"}],"shouldDisplayMessage":false,"stepsCount":1,"attachmentsCount":0,"hasContent":true},{"name":"get section[id=\"slider\"]","time":{"start":1735980003651,"stop":1735980003666,"duration":15},"status":"passed","steps":[{"name":"assert expected <section#slider> to be visible","time":{"start":1735980003666,"stop":1735980003666,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"subject","value":"<section id=\"slider\">...</section>"}],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":true}],"attachments":[],"parameters":[{"name":"Selector","value":"section[id=\"slider\"]"},{"name":"Yielded","value":"<section id=\"slider\">...</section>"},{"name":"Elements","value":"1"}],"shouldDisplayMessage":false,"stepsCount":1,"attachmentsCount":0,"hasContent":true},{"name":"get .left-sidebar","time":{"start":1735980003667,"stop":1735980003680,"duration":13},"status":"passed","steps":[{"name":"assert expected <div.left-sidebar> to be visible","time":{"start":1735980003679,"stop":1735980003680,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"subject","value":"<div class=\"left-sidebar\">...</div>"}],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":true}],"attachments":[],"parameters":[{"name":"Selector","value":".left-sidebar"},{"name":"Yielded","value":"<div class=\"left-sidebar\">...</div>"},{"name":"Elements","value":"1"}],"shouldDisplayMessage":false,"stepsCount":1,"attachmentsCount":0,"hasContent":true},{"name":"get .features_items","time":{"start":1735980003681,"stop":1735980003692,"duration":11},"status":"passed","steps":[{"name":"assert expected <div.features_items> to be visible","time":{"start":1735980003692,"stop":1735980003692,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"subject","value":"<div class=\"features_items\">...</div>"}],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":true}],"attachments":[],"parameters":[{"name":"Selector","value":".features_items"},{"name":"Yielded","value":"<div class=\"features_items\">...</div>"},{"name":"Elements","value":"1"}],"shouldDisplayMessage":false,"stepsCount":1,"attachmentsCount":0,"hasContent":true},{"name":"title","time":{"start":1735980003694,"stop":1735980003696,"duration":2},"status":"passed","steps":[{"name":"assert expected Automation Exercise to include Automation Exercise","time":{"start":1735980003696,"stop":1735980003696,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"actual","value":"Automation Exercise"}],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":true}],"attachments":[],"parameters":[{"name":"Yielded","value":"Automation Exercise"}],"shouldDisplayMessage":false,"stepsCount":1,"attachmentsCount":0,"hasContent":true}],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":13,"attachmentsCount":0,"hasContent":true}],"testStage":{"status":"broken","statusMessage":"The following error originated from your test code, not from Cypress.\n\n  > Cannot call `cy.then()` outside a running test.\n\nThis usually happens when you accidentally write commands outside an `it(...)` test.\n\nIf that is the case, just move these commands inside an `it(...)` test.\n\nCheck your test file for errors.\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.\n\nhttps://on.cypress.io/cannot-execute-commands-outside-test","statusTrace":"CypressError: The following error originated from your test code, not from Cypress.\n\n  > Cannot call `cy.then()` outside a running test.\n\nThis usually happens when you accidentally write commands outside an `it(...)` test.\n\nIf that is the case, just move these commands inside an `it(...)` test.\n\nCheck your test file for errors.\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.\n\nhttps://on.cypress.io/cannot-execute-commands-outside-test\n    at ensureRunnable (https://automationexercise.com/__cypress/runner/cypress_runner.js:137633:58)\n    at cy.<computed> [as then] (https://automationexercise.com/__cypress/runner/cypress_runner.js:138118:7)\n    at <unknown> (https://automationexercise.com/__cypress/runner/cypress_runner.js:111806:23)\n    at tryCatcher (https://automationexercise.com/__cypress/runner/cypress_runner.js:1830:23)\n    at Object.gotValue (https://automationexercise.com/__cypress/runner/cypress_runner.js:6499:18)\n    at Object.gotAccum (https://automationexercise.com/__cypress/runner/cypress_runner.js:6488:25)\n    at Object.tryCatcher (https://automationexercise.com/__cypress/runner/cypress_runner.js:1830:23)\n    at Promise._settlePromiseFromHandler (https://automationexercise.com/__cypress/runner/cypress_runner.js:1542:31)\n    at Promise._settlePromise (https://automationexercise.com/__cypress/runner/cypress_runner.js:1599:18)\n    at Promise._settlePromise0 (https://automationexercise.com/__cypress/runner/cypress_runner.js:1644:10)\n    at Promise._settlePromises (https://automationexercise.com/__cypress/runner/cypress_runner.js:1724:18)\n    at _drainQueueStep (https://automationexercise.com/__cypress/runner/cypress_runner.js:2430:12)\n    at _drainQueue (https://automationexercise.com/__cypress/runner/cypress_runner.js:2423:9)\n    at Async._drainQueues (https://automationexercise.com/__cypress/runner/cypress_runner.js:2439:5)\n    at Async.drainQueues (https://automationexercise.com/__cypress/runner/cypress_runner.js:2309:14)","steps":[],"attachments":[{"uid":"9188154796a1cc8","name":"An uncaught error was detected outside of a test (failed) (attempt 5).png","source":"9188154796a1cc8.png","type":"image/png","size":216735}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true},"afterStages":[{"name":"\"after all\" hook","time":{"start":1735980003944,"stop":1735980003945,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"labels":[{"name":"language","value":"javascript"},{"name":"framework","value":"cypress"},{"name":"host","value":"fv-az1249-509"},{"name":"thread","value":"pid-3383-worker-main"},{"name":"package","value":"cypress.e2e.cartCheckoutPayment.cy.js"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"Retry","value":"4"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"285f3966a98ab4a0","status":"broken","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > Cannot call `cy.then()` outside a running test.\n\nThis usually happens when you accidentally write commands outside an `it(...)` test.\n\nIf that is the case, just move these commands inside an `it(...)` test.\n\nCheck your test file for errors.\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.\n\nhttps://on.cypress.io/cannot-execute-commands-outside-test","time":{"start":1735979964971,"stop":1735979965965,"duration":994}}],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"bf47ba054fe53f69.json","parameterValues":["4"]}